class_based_view/account/urls.py
from django.urls import path
from . import views
from .views import(
  HomeView, RegistUserView, UserLoginView, UserLogoutView, 
  UserUpdateView, WelcomeView, UserCommentListView,CommentAddView, CommentUpdateView, CommentDeleteView
)

app_name = 'account'

urlpatterns = [
  path('home/', HomeView.as_view(), name='home'),
  path('welcome/', WelcomeView.as_view(), name='welcome'),
  path('regist/', RegistUserView.as_view(), name='regist'),
  path('user_login/', UserLoginView.as_view(), name='user_login'),
  path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
  path('user_update/<int:pk>', UserUpdateView.as_view(), name='user_update'),
  path('list_comment/<int:pk>', UserCommentListView.as_view(), name='list_comment'),
  path('add_comment/', CommentAddView.as_view(), name='add_comment'),
  path('update_comment/<int:pk>', CommentUpdateView.as_view(), name='update_comment'),
  path('delete_comment/<int:pk>', CommentDeleteView.as_view(), name='delete_comment'),
]

class_based_view/class_based_view/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('house/', include('house.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

class_based_view/house/urls.py
from django.urls import path
from .views import HomeView, HouseDetailView, HousingListView, HouseCreateView, HouseUpdateView, HouseDeleteView, delete_picture
from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView
from . import views

app_name = 'house'

urlpatterns = [
  path('house_detail/<int:pk>', HouseDetailView.as_view(), name='house_detail'),
  path('list_house/', views.HousingListView.as_view(), name='list_house'),
  path('house_add/', HouseCreateView.as_view(), name='house_add'),
  path('house_update/<int:pk>', HouseUpdateView.as_view(), name='house_update'),
  path('house_delete/<int:pk>', HouseDeleteView.as_view(), name='house_delete'),
  path('google/', RedirectView.as_view(url='http://google.co.jp')),
  path('delete_picture/<int:pk>', delete_picture, name='delete_picture'),
]

class_based_view/templates/base.html
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        {% if user.is_active %}
        <a class="navbar-brand" href="{% url 'account:home' %}">ホーム画面</a>
        <a class="navbar-brand" href="{% url 'account:user_logout' %}">ログアウト</a>
        <a class="navbar-brand" href="{% url 'house:list_house'  %}">物件一覧画面</a>
        <a class="navbar-brand" href="{% url 'account:user_update' user.id %}">ユーザー情報更新</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'account:welcome' %}">welcome画面です</a>
        {% endif %}
      </nav>
      {% block content %}{% endblock %}
   </body>
</html>