class_based_view/account/urls.py
from django.urls import path
from . import views
from .views import(
  HomeView, RegistUserView, UserLoginView, UserLogoutView, 
  UserUpdateView, WelcomeView, UserCommentListView,CommentAddView, CommentUpdateView, CommentDeleteView
)

app_name = 'account'

urlpatterns = [
  path('home/', HomeView.as_view(), name='home'),
  path('welcome/', WelcomeView.as_view(), name='welcome'),
  path('regist/', RegistUserView.as_view(), name='regist'),
  path('user_login/', UserLoginView.as_view(), name='user_login'),
  path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
  path('user_update/<int:pk>', UserUpdateView.as_view(), name='user_update'),
  path('list_comment/<int:pk>', UserCommentListView.as_view(), name='list_comment'),
  path('add_comment/', CommentAddView.as_view(), name='add_comment'),
  path('update_comment/<int:pk>', CommentUpdateView.as_view(), name='update_comment'),
  path('delete_comment/<int:pk>', CommentDeleteView.as_view(), name='delete_comment'),
]

class_based_view/class_based_view/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('house/', include('house.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

class_based_view/house/urls.py
from django.urls import path
from .views import HomeView, HouseDetailView, HousingListView, HouseCreateView, HouseUpdateView, HouseDeleteView, delete_picture
from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView
from . import views

app_name = 'house'

urlpatterns = [
  path('house_detail/<int:pk>', HouseDetailView.as_view(), name='house_detail'),
  path('list_house/', views.HousingListView.as_view(), name='list_house'),
  path('house_add/', HouseCreateView.as_view(), name='house_add'),
  path('house_update/<int:pk>', HouseUpdateView.as_view(), name='house_update'),
  path('house_delete/<int:pk>', HouseDeleteView.as_view(), name='house_delete'),
  path('google/', RedirectView.as_view(url='http://google.co.jp')),
  path('delete_picture/<int:pk>', delete_picture, name='delete_picture'),
]

class_based_view/house/forms.py
from django import forms #絶対必要
from .models import Housings, HousingPictures #booksにデータをそうにゅうするため
from datetime import datetime #現在時刻を表記するため
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import AuthenticationForm
from django.core.validators import RegexValidator
import re
from django.core.exceptions import ValidationError
from django.utils import timezone

class HouseAddForm(forms.ModelForm):
    error_css_class = 'text-danger'
    name = forms.CharField(label='物件名')
    zip_code = forms.CharField(
        label='郵便番号',
        validators=[RegexValidator(
            regex=r'^[0-9０-９]{7}$',  # 7桁の半角・全角数字のみ許可
            message='7桁の数字のみ入力してください。',
        )],
        widget=forms.TextInput(attrs={'placeholder': '例: 1234567'})
    )
    address = forms.CharField(label='住所')
    distance = forms.CharField(label='最寄駅からの距離')
    price = forms.IntegerField(
        label='家賃', 
        min_value=10000, 
        widget=forms.NumberInput(attrs={'step': '1000'})  # 1000単位で増減
    )
    FLOOR_CHOICES = [
        ('1R', '1R'),
        ('1K', '1K'),
        ('1DK', '1DK'),
        ('1LDK', '1LDK'),
        ('2DK', '2DK'),
        ('2LDK', '2LDK'),
        ('3DK', '3DK'),
        ('3LDK', '3LDK'),
    ]
    floor = forms.ChoiceField(
        label='間取り', 
        choices=FLOOR_CHOICES
    )
    house_kind = forms.CharField(label='物件の種類', initial='賃貸')
    construction = forms.IntegerField(label='築年数', min_value=1)
    floor_number = forms.IntegerField(label='階数', min_value=1)
    building_picture = forms.FileField(label='物件写真', required=False)
    floor_plan = forms.FileField(label='間取り図', required=False)

    class Meta:
        model = Housings
        fields = ['name', 'zip_code', 'address', 'distance', 'price', 'floor', 'house_kind', 'construction', 'floor_number', 'building_picture', 'floor_plan']
    
    # nameフィールドのバリデーション
    def clean_name(self):
      name = self.cleaned_data.get('name')
      if not name:
        raise ValidationError('物件名は必須です。')
      if ' ' in name:
        raise ValidationError('物件名にスペースを含めることはできません。')
      if '@' in name:
        raise ValidationError('物件名に「@」を含めることはできません。')
      return name

    # 全体のバリデーション
    def clean(self):
      cleaned_data = super().clean()
      price = cleaned_data.get('price')
      distance = cleaned_data.get('distance')
      
      if price is not None and price < 1000:
        if not distance:
          raise ValidationError('家賃が安すぎます。適正な価格を記載ください。または最寄駅からの距離を入力する必要があります。')
        
        # 物件名と住所の組み合わせがユニークかどうかのチェック
      name = cleaned_data.get('name')
      address = cleaned_data.get('address')
      if not self.instance.pk:  # 新規作成時のみチェック
        if Housings.objects.filter(name=name, address=address).exists():
          raise ValidationError('同じ物件名と住所の組み合わせが既に存在しています。')
    
    def save(self, *args, **kwargs):
      obj = super(HouseAddForm, self).save(commit=False)
      obj.create_at = timezone.now()
      obj.update_at = timezone.now()
      obj.save()

      if self.cleaned_data['building_picture']:
        building_picture = HousingPictures.objects.create(
        picture=self.cleaned_data['building_picture'],  # ここでファイルを保存
        housing=obj,  # 関連付けるHousingsインスタンス
        picture_type='building',  # picture_typeを指定
        order=1
        )
        print(f"Building picture saved: {building_picture}")
        obj.building_picture = building_picture  # ForeignKeyにセット

      if self.cleaned_data['floor_plan']:
        floor_plan = HousingPictures.objects.create(
        picture=self.cleaned_data['floor_plan'],
        housing=obj,
        picture_type='floor',  # picture_typeを指定
        order=2
        )
        print(f"Floor plan saved: {floor_plan}") 
        obj.floor_plan = floor_plan

      obj.save()
      return obj

class HouseUpdateForm(forms.ModelForm):
    error_css_class = 'text-danger'
    name = forms.CharField(label='物件名')
    zip_code = forms.CharField(
        label='郵便番号',
        validators=[RegexValidator(
            regex=r'^[0-9０-９]{7}$',  # 7桁の半角・全角数字のみ許可
            message='7桁の数字のみ入力してください。',
        )],
        widget=forms.TextInput(attrs={'placeholder': '例: 1234567'})
    )
    address = forms.CharField(label='住所')
    distance = forms.CharField(label='最寄駅からの距離')
    price = forms.IntegerField(
        label='家賃', 
        min_value=10000, 
        widget=forms.NumberInput(attrs={'step': '1000'})  # 1000単位で増減
    )
    FLOOR_CHOICES = [
        ('1R', '1R'),
        ('1K', '1K'),
        ('1DK', '1DK'),
        ('1LDK', '1LDK'),
        ('2DK', '2DK'),
        ('2LDK', '2LDK'),
        ('3DK', '3DK'),
        ('3LDK', '3LDK'),
    ]
    floor = forms.ChoiceField(
        label='間取り', 
        choices=FLOOR_CHOICES
    )
    house_kind = forms.CharField(label='物件の種類', initial='賃貸')
    construction = forms.IntegerField(label='築年数', min_value=1)
    floor_number = forms.IntegerField(label='階数', min_value=1)
    building_picture = forms.FileField(label='物件写真', required=False)
    floor_plan = forms.FileField(label='間取り図', required=False)

    class Meta:
        model = Housings
        fields = ['name', 'zip_code', 'address', 'distance', 'price', 'floor', 'house_kind', 'construction', 'floor_number', 'building_picture', 'floor_plan']
      
        # nameフィールドのバリデーション
    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not name:
            raise ValidationError('物件名は必須です。')
        elif '  ' in name:
          raise ValidationError('物件名にスペースキーを使用しないでください')
        elif ' ' in name:
          raise ValidationError('物件名にスペースキーを使用しないでください')
        return name

    # 全体のバリデーション
    def clean(self):
        cleaned_data = super().clean()

        price = cleaned_data.get('price')
        distance = cleaned_data.get('distance')
        
        if price is not None and price < 1000:
            if not distance:
                raise ValidationError('家賃が安すぎます。適正な価格を記載ください。または最寄駅からの距離を入力する必要があります。')

        # 物件名と住所の組み合わせがユニークかどうかのチェック
        name = cleaned_data.get('name')
        address = cleaned_data.get('address')
        if not self.instance.pk:  # 新規作成時のみチェック
            if Housings.objects.filter(name=name, address=address).exists():
                raise ValidationError('同じ物件名と住所の組み合わせが既に存在しています。')

        return cleaned_data
      
    def save(self, *args, **kwargs):
        obj = super(HouseUpdateForm, self).save(commit=False)
        obj.update_at = timezone.now()
        obj.save()
        return obj
  
class PictureUploadForm(forms.ModelForm):
  error_css_class = 'text-danger'
  building_picture = forms.FileField(required=False)
  floor_plan = forms.FileField(required=False)
  
  class Meta:
    model = HousingPictures
    fields = ['building_picture','floor_plan']
  
  def save(self, house=None, *args, **kwargs):
        obj = super(PictureUploadForm, self).save(commit=False)
        obj.create_at = timezone.now()
        obj.update_at = timezone.now()
        
        if house:
            obj.house = house
        
        if self.cleaned_data.get('building_picture'):
          obj.save()  # HousingPictures モデルを保存
        elif self.cleaned_data.get('floor_plan'):
          obj.save()  # HousingPictures モデルを保存
        return obj
      
class PictureCreateForm(forms.ModelForm):
  error_css_class = 'text-danger'
  building_picture = forms.FileField(required=False)
  floor_plan = forms.FileField(required=False)
  
  class Meta:
    model = HousingPictures
    fields = ['building_picture','floor_plan']
  
  def save(self, house=None, *args, **kwargs):
        obj = super(PictureCreateForm, self).save(commit=False)
        obj.create_at = timezone.now()
        obj.update_at = timezone.now()
        
        if house:
            obj.house = house
        
        if self.cleaned_data.get('building_picture'):
          obj.save()  # HousingPictures モデルを保存
        elif self.cleaned_data.get('floor_plan'):
          obj.save()  # HousingPictures モデルを保存
        return obj

class_based_view/house/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import (
  View,TemplateView,RedirectView
)
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import (
  CreateView, UpdateView, DeleteView, FormView,
)
from . import forms
from datetime import datetime
from django.contrib import messages
from .models import Housings, HousingPictures
from django.urls import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin
from .forms import PictureUploadForm, HouseAddForm, HouseUpdateForm, PictureCreateForm
import logging
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
import os

# application_logger = logging.getLogger('application-logger') #settings.pyのloggersに記載しているので呼び出すと記載の設定で作成してくれる。
# error_logger= logging.getLogger('error-logger')
    
class HomeView(TemplateView):
  template_name = 'account/home.html'

class HouseDetailView(LoginRequiredMixin,DetailView):
  model = Housings
  template_name = os.path.join('house', 'house_detail.html')
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    housing_pictures = HousingPictures.objects.filter(housing=self.object)
    context['housing_pictures'] = housing_pictures
    return context
  
class HousingListView(ListView):
  model = Housings #一覧表示するモデル
  template_name = 'house/list_house.html' #表示するテンプレートの名前
  
  def get_queryset(self):
    query = super().get_queryset()
    name = self.request.GET.get('housing.name', None)
    if name:
      query = query.filter(
        name__icontains = name
      )
    distance = self.request.GET.get('housing.distance', None)
    if distance:
      query = query.filter(
        distance__icontains = distance
      )
    order_by_price = self.request.GET.get('order_by_price', 0)
    if order_by_price == '1':
      query = query.order_by('price')
    elif order_by_price == '2':
      query = query.order_by('-price')
    return query
    
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['housing.name'] = self.request.GET.get('housing.name', '')
    context['housing.distance'] = self.request.GET.get('housing.distance', '')
    order_by_price = self.request.GET.get('order_by_price')
    if order_by_price == '1':
      context['ascending'] = True
    elif order_by_price == '2':
      context['descending'] = True
    return context
  
class HouseCreateView(CreateView):
  model = Housings
  template_name = 'house/house_add.html'
  form_class = HouseAddForm
  success_message = '物件登録が完了しました'
  
  def get_success_url(self):
        return reverse_lazy('house:list_house')
   
  def get_success_message(self, cleaned_data):
        return f'{cleaned_data.get("name")}を登録しました'
  
  def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['picture_form'] = PictureCreateForm()  # PictureCreateFormを追加
        return context
  
class HouseUpdateView(SuccessMessageMixin, UpdateView):
    template_name = 'house/house_update.html'
    model = Housings
    form_class = forms.HouseUpdateForm
    success_message = '更新に成功しました'

    def get_success_url(self):
        return reverse('house:list_house')

    def get_success_message(self, cleaned_data):
        return cleaned_data.get('name') + 'を更新しました'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['picture_form'] = PictureUploadForm() 
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        picture_form = PictureUploadForm(request.POST, request.FILES)
        
        if form.is_valid() and picture_form.is_valid():
            # HouseUpdateFormの情報を保存
            updated_house = form.save(commit=False)
            updated_house.update_at = datetime.now()  # 更新日時を設定
            updated_house.save()

            if 'building_picture' in request.FILES:
              for file in request.FILES.getlist('building_picture'):
                HousingPictures.objects.create(
                  housing=self.object,
                  picture=file,
                  picture_type='building'
              )
            if 'floor_plan' in request.FILES:
              for file in request.FILES.getlist('floor_plan'):
                HousingPictures.objects.create(
                  housing=self.object,
                  picture=file,
                  picture_type='floor'
              )
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
  
class HouseDeleteView(DeleteView):
  model = Housings
  template_name = 'house/house_delete.html'
  success_url = reverse_lazy('house:list_house')
  
def delete_picture(request, pk):
  picture = get_object_or_404(HousingPictures, pk=pk)
  picture.delete()
  import os
  if os.path.isfile(picture.picture.path):
    os.remove(picture.picture.path)
  messages.success(request, '画像を削除しました')
  return redirect('store:edit_book', pk=picture.book.id)

class_based_view/templates/house/house_add.html
{% extends "base.html" %}
{% block content %}
<div style='text-align: center;'>
  <h2>物件新規登録画面です。</h2>
  <h5>以下のフォームより入力いただき、物件登録ボタンを押してください。</h5>
  <hr>
  <a class="navbar-brand" href="{% url 'house:list_house'  %}">物件一覧画面へ戻る</a>
  <hr>
  <form method="post">
  {% csrf_token %}
    <table align='center'>
      {{ form.as_table }}
   </table>
    <hr>
    <button type="submit">物件登録</button>
  </form>
</div>

<style>
  /* テーブル全体のスタイル */
  .form-table {
    width: 50%;
    margin: 0 auto;
  }

  /* 全ての入力フィールド、セレクトボックス、ファイル入力を同じ幅に設定 */
  input[type="text"],
  select,
  input[type="number"],
  input[type="file"] {
    width: 100%;
    padding: 5px;
    box-sizing: border-box;
  }

  /* ファイルアップロードのラベルとフィールドの調整 */
  input[type="number"],
  input[type="file"] {
    text-align: left;
  }
</style>
{% endblock %}

class_based_view/templates/house/house_delete.html
{% extends "base.html" %}
{% block content %}
<form method='POST'>
{% csrf_token %}
<div style='text-align: center;'>
  <p>{{ object.name }}を削除してよろしいでしょうか？</p>
  <input type='submit' value='削除する'>
  </form>
  <hr>
  <a class="navbar-brand" href="{% url 'house:list_house'  %}">物件一覧画面へ戻る</a>
</div>
{% endblock %}

class_based_view/templates/house/house_detail.html
{% extends 'base.html' %}
{% block content %}
<div style='text-align: center;'>
  <h2>{{ housings.name }}の詳細画面です</h2>
  <h6>下記より口コミの投稿・閲覧いただけます</h6>
  <hr>
   {# 物件写真の表示 #}
{# 物件写真の表示 #}
{% for picture in housing_pictures %}
  {% if picture.picture_type == 'building' %}
    <div>
      <h4>物件写真</h4>
      <img width='305px' height='320px' src="{{ picture.picture.url }}" alt="物件写真">
    </div>
  {% endif %}
{% empty %}
  <p>物件写真は登録されていません。</p>
{% endfor %}

{# 間取り図の表示 #}
{% for picture in housing_pictures %}
  {% if picture.picture_type == 'floor' %}
    <div>
      <h4>間取り図</h4>
      <img width='305px' height='320px' src="{{ picture.picture.url }}" alt="間取り図">
    </div>
  {% endif %}
{% empty %}
  <p>間取り図は登録されていません。</p>
{% endfor %}
  <div>
    <p>物件名: {{ object.name }}</p>
    <p>郵便番号: {{ object.zip_code }}</p>
    <p>住所: {{ object.address }}</p>
    <p>最寄駅からの距離: {{ object.distance }}</p>
    <p>家賃: {{ object.price }}円</p>
    <p>間取り: {{ object.floor }}</p>
    <p>物件の種類: {{ object.house_kind }}</p>
    <p>築年数: {{ object.construction }}年</p>
    <p>階数: {{ object.floor_number }}階</p>
  </div>
  <hr>
  <table class="table table-striped table-bordered">
  <tbody>
    <td><a href='{% url 'account:list_comment' object.id %}'>口コミ一覧ページへ</a></td>
    <td><a href='{% url 'house:list_house' %}'>物件一覧に戻る</a></td>
  </tbody>
  </table>
</div>
{% endblock %}

class_based_view/templates/house/house_update.html
{% extends 'base.html' %}
{% block content %}
<div style='text-align: center;'>
 
  <form method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    <table align='center'>
      {{ form.as_table }}
    </table>

    {% if form.errors %}
      <div style="color: red;">
        <ul>
          {% for field, errors in form.errors.items %}
            <li>{{ field }}: {{ errors|striptags }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}

    <input type='submit' value='更新'>
  </form>
  <hr>
  <a class="navbar-brand" href="{% url 'house:list_house'  %}">物件一覧画面へ戻る</a>
<div>

<style>
  /* テーブル全体のスタイル */
  .form-table {
    width: 50%;
    margin: 0 auto;
  }

  /* 全ての入力フィールドを同じ幅に設定 */
  input[type="text"],
  select,
  input[type="number"],
  input[type="file"] {
    width: 100%;
    padding: 5px;
    box-sizing: border-box;
  }

  /* ファイルアップロードのラベルとフィールドの調整 */
  input[type="number"],
  input[type="file"] {
    text-align: left;
  }
</style>
{% endblock %}

class_based_view/templates/house/list_house.html
{% extends 'base.html' %}
{% block content %}
<div style='text-align: center;'>
  <h1>物件一覧ページです</h1>
  <hr>

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endfor %}
  {% endif %}

  {% if user.is_staff %}
  <p><a href='{% url 'house:house_add' %}'>物件新規登録</a></p>
  {% endif %}
  <p><a href='{% url 'account:home' %}'>ホーム画面へ戻る</a></p>
  <hr>
  <form method='get' action='{% url 'house:list_house' %}'>
    <p>物件名: <input type='text' name='housing.name' value='{{ housing.name }}'/></p>
    <p>最寄駅からの距離: <input type='text' name='housing.distance' value='{{ housing.distance }}'/></p>
    <p>値段で並び替える:
      昇順<input type='radio' name='order_by_price' value='1' {% if ascending %}checked{% endif %}>
      降順<input type='radio' name='order_by_price' value='2' {% if descending %}checked{% endif %}>
    </p>
    <p><input type='submit' value='実行する'/></p>
  </form>
  <hr>
  <table class="table table-striped table-bordered">
  <thead>
    <tr>
        <td>名前</td>
        <td>最寄駅からの距離</td>
        <td>住所</td>
        <td>間取り</td>
        <td>家賃</td>
    </tr>
  </thead>
  <tbody>
  {% for housing in object_list %}
    <tr>
      <td><a href='{% url 'house:house_detail' pk=housing.id %}'>{{ housing.name }}</a></td>
      <td>{{ housing.distance }}</td>
      <td>{{ housing.address }}</td>
      <td>{{ housing.floor }}</td>
      <td>{{ housing.price }}円</td>
    {% if user.is_staff %}
      <td><a href='{% url 'house:house_update' pk=housing.id %}'>編集</a></td>
      <td><a href='{% url 'house:house_delete' pk=housing.id %}'>削除</a></td>
    {% endif %}
    
    </tr>
  {% endfor %}
  </tbody>
</div>
{% endblock %}